spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:~/cast_magazine;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

liquibase:
  enabled: true
  change-log: classpath:changelogs/db.changelog-master.xml
